name: Run Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ python3 python3-pip
          pip3 install pytest

      - name: Build C++ files
        run: |
          find . -name "*.cpp" -print0 | while IFS= read -r -d $'\0' file; do
            dir=$(dirname "$file")
            mkdir -p "build/$dir"
            filename=$(basename "$file" .cpp)
            g++ -o "build/$dir/$filename" "$file"
          done

      - name: Run C++ tests
        run: |
          if [ -d "tests" ]; then
            for test in tests/*.cpp; do
              test_name=$(basename "$test" .cpp)
              if [ -f "tests/${test_name}.in" ]; then
                ./build/tests/$test_name < "tests/${test_name}.in" > "tests/${test_name}.out"
                if ! diff "tests/${test_name}.out" "tests/${test_name}.expected"; then
                  echo "Test $test_name failed!"
                  exit 1
                fi
              fi
            done
          fi

      - name: Run Python tests
        run: |
          if [ -d "tests" ]; then
            python3 -m pytest tests/
          fi
